FROM postgres:15

ENV POSTGRES_USER=security-user
ENV POSTGRES_PASSWORD=abc1

ENV POSTGRES_DB=futebol-amigo

EXPOSE 5432

# docker build -t meu-postgres .
# docker run -d -p 5432:5432 --name meu-postgres-container meu-postgres